### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by JunMa11** [niki-amini-naieni/CountGD#1]
Thanks for sharing the amazing work!

Would it be possible to let us know when the training code will be available?

**Comment by hongge831** [comment]
@niki-amini-naieni I also wonder when the training code will be avaliable?

**Comment by niki-amini-naieni** [comment]
Hello, thank you very much for your interest! I am aiming to put it up by the time the paper is accepted or sooner.

**Comment by vincentlux** [comment]
hi @niki-amini-naieni , thanks a lot for the work! This is amazing. I wonder if you still have plan to release the training code for this? That would be super helpful. Thanks in advance!

**Comment by niki-amini-naieni** [comment]
Thank you! Yes, I have not had a chance to do this yet though.

**Comment by vincentlux** [comment]
That's awesome! thanks and looking forward to it!

**Comment by PhamThinh31** [comment]
hi @niki-amini-naieni 

I hope you're well. I saw your response regarding the release of the training code in Issue #1. I understand the delay, and I appreciate your efforts. I was wondering if you have any updates or an expected timeline for the release?

**Comment by niki-amini-naieni** [comment]
Hi, thank you for your interest. The code and instructions are now available here: https://github.com/niki-amini-naieni/CountGD/blob/main/training.md.
