### ISSUE TITLE
Training VRAM

### ISSUE THREAD

**Issue by lp-094** [niki-amini-naieni/CountGD#11]
How much video memory is needed for training?

**Comment by niki-amini-naieni** [comment]
One of these GPUs was enough for me:
![image](https://github.com/user-attachments/assets/bf726cf7-3479-4ccc-aec8-8c1d5daaafa3)

**Comment by lp-094** [comment]
thank you




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Niki ***@***.***&gt;; 
发送时间: 2024年9月5日(星期四) 下午2:24
收件人: ***@***.***&gt;; 
抄送: "happy ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [niki-amini-naieni/CountGD] Training VRAM (Issue #11)














 
One of these GPUs was enough for me:
 image.png (view on web)
