### ISSUE TITLE
谁能帮我写一个测试用例，通过调用接口传入图片来实现效果

### ISSUE THREAD

**Issue by via007** [niki-amini-naieni/CountGD#12]
我想要个测试用例，就是我输入图片和文字，计算我的结果。现在可以安装readme整个流程跑通，就是不知道怎么应用。

**Comment by niki-amini-naieni** [comment]
Hi,

Thank you for your question. You can use the app available here as a testing interface: [CountGD_Multi-Modal_Open-World_Counting - a Hugging Face Space by nikigoli](https://huggingface.co/spaces/nikigoli/countgd). If you go to the "App" tab shown below, you can input text, or visual exemplars, or both together with the input image to test out the model.

![image](https://github.com/user-attachments/assets/7c48a389-9f88-4c56-a461-48585b510b5e)

You can use docker to get the app locally via the following command:
docker run -it -p 7860:7860 --platform=linux/amd64 --gpus all \
      registry.hf.space/nikigoli-countgd:latest python app.py

To test your own model, you can just change the pretrained checkpoint in app.py as shown below:
![image](https://github.com/user-attachments/assets/80f71288-549b-4cb3-b65b-577264e29320)
