### ISSUE TITLE
Training Guidance

### ISSUE THREAD

**Issue by yashsinha1702** [niki-amini-naieni/CountGD#13]
Thanks for sharing your work on CountGD. I’m interested in training the model from scratch on my device . Could you please kindly provide some guidance on how I can set it up and train the model on my own? I’d really appreciate any help. Thanks!

**Comment by niki-amini-naieni** [comment]
Hi, thank you for your interest. The code and instructions are now available here: https://github.com/niki-amini-naieni/CountGD/blob/main/training.md.
