### ISSUE TITLE
how to use vis_picture in single image

### ISSUE THREAD

**Issue by chwang589** [niki-amini-naieni/CountGD#15]
Hello @niki-amini-naieni,

I hope you're doing well. I've been using your CountGD demo to create a script for single image inference, and it's been working great! However, I'm now looking to enhance the functionality by incorporating keypoint images as auxiliary data into the single image processing. I'm having some trouble figuring out how to modify the existing script to achieve this.

Here's the script I'm working with:

# 
import argparse
import torch
import numpy as np
from PIL import Image, ImageDraw, ImageFont
import os
from tqdm import tqdm

from util.slconfig import SLConfig
from util.misc import nested_tensor_from_tensor_list
import datasets.transforms as T
from models.registry import MODULE_BUILD_FUNCS

def get_args_parser():
    parser = argparse.ArgumentParser("CountGD Single Image Inference", add_help=False)
    parser.add_argument("--config", default="cfg_app.py", help="path to config file")
    parser.add_argument("--checkpoint", default="", help="path to model checkpoint")
    parser.add_argument("--input_folder", required=True, help="path to input folder containing images")
    parser.add_argument("--output_folder", required=True, help="path to output folder for processed images")
    parser.add_argument("--text", default="", help="text description of object to count")
    parser.add_argument("--device", default="cuda:0" if torch.cuda.is_available() else "cpu", help="device to use for inference")
    return parser

def build_model_and_transforms(args):
    cfg = SLConfig.fromfile(args.config)
    cfg.device = args.device
    cfg.merge_from_dict({"text_encoder_type": "checkpoints/bert-base-uncased"})

    transform = T.Compose([
        T.RandomResize([800], max_size=1333),
        T.ToTensor(),
        T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    build_func = MODULE_BUILD_FUNCS.get(cfg.modelname)
    model, _, _ = build_func(cfg)

    checkpoint = torch.load(args.checkpoint, map_location="cpu")["model"]
    model.load_state_dict(checkpoint, strict=False)
    model.to(args.device)
    model.eval()

    return model, transform

def process_image(model, transform, image_path, text, device):
    image = Image.open(image_path).convert("RGB")
    w, h = image.size
    
    target = {
        "size": torch.tensor([h, w]),
        "orig_size": torch.tensor([h, w]),
        "exemplars": torch.zeros((0, 4))
    }
    
    input_image, _ = transform(image, target)
    input_image = input_image.unsqueeze(0).to(device)

    samples = nested_tensor_from_tensor_list([input_image.squeeze(0)])
    exemplars = [torch.zeros((0, 4)).to(device)]
    labels = torch.zeros((1, 0), dtype=torch.long).to(device)
    
    targets = [{
        "image_id": torch.tensor([0]),
        "annotations": [],
        "caption": text + " .",
        "exemplars": torch.zeros((0, 4)).to(device)
    }]

    with torch.no_grad():
        model_output = model(samples, exemplars, labels, targets)
    
    logits = model_output["pred_logits"].sigmoid()[0]
    boxes = model_output["pred_boxes"][0]
    
    CONF_THRESH = 0.20
    scores = logits.max(dim=-1).values
    box_mask = scores > CONF_THRESH
    boxes = boxes[box_mask].cpu().numpy()
    scores = scores[box_mask].cpu().numpy()

    print(f"Detected center points count: {len(boxes)}")
    
    return image, boxes, scores

def plot_results(image, boxes, scores, output_path):
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default()

    color = "red"
    radius = 5  # 定义圆点的半径
    for box, score in zip(boxes, scores):
        box = box * np.array([image.width, image.height, image.width, image.height])
        x_c, y_c, w, h = box
        # 获取中心点坐标
        x0, y0 = x_c, y_c

        # 确保中心点在图像范围内
        x0 = max(0, min(x0, image.width - 1))
        y0 = max(0, min(y0, image.height - 1))

        # 绘制中心点为红色的圆圈
        draw.ellipse([x0 - radius, y0 - radius, x0 + radius, y0 + radius], outline=color, width=2)

    image.save(output_path)

def main(args):
    model, transform = build_model_and_transforms(args)
    
    os.makedirs(args.output_folder, exist_ok=True)
    
    image_files = [f for f in os.listdir(args.input_folder) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif'))]
    
    for image_file in tqdm(image_files, desc="Processing images"):
        input_path = os.path.join(args.input_folder, image_file)
        output_path = os.path.join(args.output_folder, f"{os.path.splitext(image_file)[0]}_counted.png")
        
        image, boxes, scores = process_image(model, transform, input_path, args.text, args.device)
        plot_results(image, boxes, scores, output_path)
        
        print(f"Processed {image_file}. Predicted count: {boxes.shape[0]}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser("CountGD Single Image Inference", parents=[get_args_parser()])
    args = parser.parse_args()
    main(args)

I would like to add the capability to include keypoint images alongside the main image for better inference results. Could you please provide some guidance on how I could modify the script to accommodate this?

Specifically, I'm unsure about:

How to load and preprocess the keypoint images.
How to integrate these keypoint images into the model's input pipeline.
Any changes needed in the model architecture or inference logic to effectively use these keypoints.
I appreciate any help you can provide. Thank you for your time and for creating such a useful tool!

Best regard!

**Comment by niki-amini-naieni** [comment]
Hi @chwang589, thank you for the interest and for the question! Could you please clarify what you mean by a *keypoint image*? Do you mean an image used to extract visual exemplars (bounding boxes over example instances) to specify the object to count or something else?

**Comment by chwang589** [comment]
Hi @niki-amini-naieni

Thank you for your prompt response. By "keypoint image," I mean an image that contains visual exemplars which are used to assist in the counting process. These exemplars are essentially sample instances of the objects we're interested in counting, and they might be highlighted with bounding boxes to clearly indicate the areas of interest within the image.

**Comment by niki-amini-naieni** [comment]
Here is a short answer that I can provide quickly. If you need more help, I can go into depth.

In this file: https://huggingface.co/spaces/nikigoli/countgd/blob/main/app.py, I use an "exemplar image," which you call a "keypoint image." Using the code in the app, you can provide visual exemplars as shown below for reference:
<img width="676" alt="image" src="https://github.com/user-attachments/assets/9a261b58-395d-44b1-9a53-4b2a44407228">
The image containing the exemplars is referred to as ```input_image_exemplars``` (highlighted in yellow). The exemplar bounding boxes are in ```exemplars``` (highlighted in blue).

**Comment by chwang589** [comment]
Thank you very much! I will try it myself first.

**Comment by niki-amini-naieni** [comment]
Great, let me know how it goes!

**Comment by chwang589** [comment]
Hello Niki Amini Naieni,

I integrated the bounding box feature into the script, but I noticed that adding the boxes did not improve the accuracy compared to using only text. The precision seems to remain unchanged. Here is the script I used:import argparse
import torch
import numpy as np
from PIL import Image, ImageDraw, ImageFont
import os
from tqdm import tqdm
import json
from util.slconfig import SLConfig
from util.misc import nested_tensor_from_tensor_list
import datasets.transforms as T
from models.registry import MODULE_BUILD_FUNCS

def get_args_parser():
    parser = argparse.ArgumentParser("CountGD Single Image Inference", add_help=False)
    parser.add_argument("--config", default="cfg_app.py", help="path to config file")
    parser.add_argument("--checkpoint", default="", help="path to model checkpoint")
    parser.add_argument("--input_folder", required=True, help="path to input folder containing images")
    parser.add_argument("--output_folder", required=True, help="path to output folder for processed images")
    parser.add_argument("--text", default="")
    parser.add_argument("--exemplars", default=None, help="path to file containing exemplars (bounding boxes) for input images")
    parser.add_argument("--device", default="cpu" if torch.cuda.is_available() else "cpu", help="device to use for inference")
    return parser

def build_model_and_transforms(args):
    cfg = SLConfig.fromfile(args.config)
    cfg.device = args.device
    cfg.merge_from_dict({"text_encoder_type": "checkpoints/bert-base-uncased"})

    transform = T.Compose([
        T.RandomResize([800], max_size=1333),
        T.ToTensor(),
        T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
    ])

    build_func = MODULE_BUILD_FUNCS.get(cfg.modelname)
    model, _, _ = build_func(cfg)

    checkpoint = torch.load(args.checkpoint, map_location="cpu")["model"]
    model.load_state_dict(checkpoint, strict=False)
    model.to(args.device)
    model.eval()

    return model, transform

def process_image(model, transform, image_path, text, device, exemplars=None):
    image = Image.open(image_path).convert("RGB")
    w, h = image.size

    target = {
        "size": torch.tensor([h, w]),
        "orig_size": torch.tensor([h, w]),
        "exemplars": torch.zeros((0, 4)) if exemplars is None else torch.tensor(exemplars)
    }
    
    input_image, _ = transform(image, target)
    input_image = input_image.unsqueeze(0).to(device)

    samples = nested_tensor_from_tensor_list([input_image.squeeze(0)])
    exemplars_tensor = [torch.zeros((0, 4)).to(device)] if exemplars is None else [torch.tensor(exemplars).to(device)]
    labels = torch.zeros((1, 0), dtype=torch.long).to(device)
    
    targets = [{
        "image_id": torch.tensor([0]),
        "annotations": [],
        "caption": text + " .",
        "exemplars": exemplars_tensor[0]
    }]

    with torch.no_grad():
        model_output = model(samples, exemplars_tensor, labels, targets)
    
    logits = model_output["pred_logits"].sigmoid()[0]
    boxes = model_output["pred_boxes"][0]
    
    CONF_THRESH = 0.10
    scores = logits.max(dim=-1).values
    box_mask = scores > CONF_THRESH
    boxes = boxes[box_mask].cpu().numpy()
    scores = scores[box_mask].cpu().numpy()

    print(f"Detected center points count: {len(boxes)}")
    
    return image, boxes, scores

def plot_results(image, boxes, scores, output_path):
    draw = ImageDraw.Draw(image)
    font = ImageFont.load_default()

    color = "red"
    radius = 5  # 定义圆点的半径
    for box, score in zip(boxes, scores):
        box = box * np.array([image.width, image.height, image.width, image.height])
        x_c, y_c, w, h = box
        # 获取中心点坐标
        x0, y0 = x_c, y_c

        # 确保中心点在图像范围内
        x0 = max(0, min(x0, image.width - 1))
        y0 = max(0, min(y0, image.height - 1))

        # 绘制中心点为红色的圆圈
        draw.ellipse([x0 - radius, y0 - radius, x0 + radius, y0 + radius], outline=color, width=2)

    image.save(output_path)

def main(args):
    model, transform = build_model_and_transforms(args)
    
    os.makedirs(args.output_folder, exist_ok=True)
    
    image_files = [f for f in os.listdir(args.input_folder) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif'))]
    
    # 如果提供了exemplar文件，将exemplars加载
    exemplars_data = None
    if args.exemplars is not None:
        with open(args.exemplars, 'r') as f:
            exemplars_data = json.load(f)

    for image_file in tqdm(image_files, desc="Processing images"):
        input_path = os.path.join(args.input_folder, image_file)
        output_path = os.path.join(args.output_folder, f"{os.path.splitext(image_file)[0]}_counted.png")
        
        # 如果提供了exemplars，使用相应的exemplar
        exemplars = None
        if exemplars_data and image_file in exemplars_data:
            exemplars = exemplars_data[image_file]

        image, boxes, scores = process_image(model, transform, input_path, args.text, args.device, exemplars)
        plot_results(image, boxes, scores, output_path)
        
        print(f"Processed {image_file}. Predicted count: {boxes.shape[0]}")

if __name__ == "__main__":
    parser = argparse.ArgumentParser("CountGD Single Image Inference", parents=[get_args_parser()])
    args = parser.parse_args()
    main(args)


Let me know if you have any suggestions or thoughts on why this might be happening or if there’s anything else we should try.

Best regards,

**Comment by niki-amini-naieni** [comment]
Did you try running the same example through the app? If you send me the example images, I can try running them through the app to see if providing exemplars improves the results. Your problem could be due to two possibilities (1) there is a bug in the way you are providing the exemplars to the model or (2) the exemplars do not add more information, so the count is not more accurate by adding them. I would recommend using the app to test (1). We found for many examples, adding exemplars does improve the results.

**Comment by niki-amini-naieni** [comment]
For example, here the exemplars help the model differentiate between the blueberries and the strawberries:
![image](https://github.com/user-attachments/assets/3adedd61-dcac-4b38-b07b-402204f7de1b)
Refer to https://github.com/niki-amini-naieni/CountGD/issues/4 for more information on this example.

**Comment by chwang589** [comment]
yes I try it in the app ,it is the same,   you can try with it

![output_无芒雀麦3](https://github.com/user-attachments/assets/1b0ab8f7-a2f7-4486-9455-df2b5934f12a)
![无芒雀麦3](https://github.com/user-attachments/assets/727641a8-a652-4965-84bd-7e033ef190fb)

**Comment by chwang589** [comment]
you can try this prompt: "individual chromosome.single blue fluorescent chromosome.isolated chromosome structure.distinct DAPI-stained chromosome.separate metaphase chromosome.individual condensed chromosome in mitosis.single elongated chromosome structure.discrete chromosome in cell division.solitary fluorescent chromosome.individual compact chromosome structure".  when I use visual exemplar ,the count of cell descent。
![image](https://github.com/user-attachments/assets/6eeac62d-9fba-45f8-9827-9e23bd766ad0)   
![image](https://github.com/user-attachments/assets/f30c6be6-732a-4189-b558-cc616f55c388)

**Comment by niki-amini-naieni** [comment]
Hi, yes, I see. I agree with you, after some experimentation, this does seem to be difficult for the model. Because you have already provided a very detailed description, in this case, the exemplar may not be adding more information.

**Comment by chwang589** [comment]
Thank you for your reply, I have a general understanding now. In fact, the description here was generated using a large model. Recently, the new open vocabulary detection framework https://github.com/FoundationVision/GenerateU uses generative models for alignment to optimize the results. Anyway, I still really appreciate your work.

**Comment by niki-amini-naieni** [comment]
Thank you for your appreciation, and I am really looking forward to reading about this!

**Comment by elvistheyo** [comment]
> Hello Niki Amini Naieni,
> 
> I integrated the bounding box feature into the script, but I noticed that adding the boxes did not improve the accuracy compared to using only text. The precision seems to remain unchanged. Here is the script I used:import argparse import torch import numpy as np from PIL import Image, ImageDraw, ImageFont import os from tqdm import tqdm import json from util.slconfig import SLConfig from util.misc import nested_tensor_from_tensor_list import datasets.transforms as T from models.registry import MODULE_BUILD_FUNCS
> 
> def get_args_parser(): parser = argparse.ArgumentParser("CountGD Single Image Inference", add_help=False) parser.add_argument("--config", default="cfg_app.py", help="path to config file") parser.add_argument("--checkpoint", default="", help="path to model checkpoint") parser.add_argument("--input_folder", required=True, help="path to input folder containing images") parser.add_argument("--output_folder", required=True, help="path to output folder for processed images") parser.add_argument("--text", default="") parser.add_argument("--exemplars", default=None, help="path to file containing exemplars (bounding boxes) for input images") parser.add_argument("--device", default="cpu" if torch.cuda.is_available() else "cpu", help="device to use for inference") return parser
> 
> def build_model_and_transforms(args): cfg = SLConfig.fromfile(args.config) cfg.device = args.device cfg.merge_from_dict({"text_encoder_type": "checkpoints/bert-base-uncased"})
> 
> ```
> transform = T.Compose([
>     T.RandomResize([800], max_size=1333),
>     T.ToTensor(),
>     T.Normalize([0.485, 0.456, 0.406], [0.229, 0.224, 0.225])
> ])
> 
> build_func = MODULE_BUILD_FUNCS.get(cfg.modelname)
> model, _, _ = build_func(cfg)
> 
> checkpoint = torch.load(args.checkpoint, map_location="cpu")["model"]
> model.load_state_dict(checkpoint, strict=False)
> model.to(args.device)
> model.eval()
> 
> return model, transform
> ```
> 
> def process_image(model, transform, image_path, text, device, exemplars=None): image = Image.open(image_path).convert("RGB") w, h = image.size
> 
> ```
> target = {
>     "size": torch.tensor([h, w]),
>     "orig_size": torch.tensor([h, w]),
>     "exemplars": torch.zeros((0, 4)) if exemplars is None else torch.tensor(exemplars)
> }
> 
> input_image, _ = transform(image, target)
> input_image = input_image.unsqueeze(0).to(device)
> 
> samples = nested_tensor_from_tensor_list([input_image.squeeze(0)])
> exemplars_tensor = [torch.zeros((0, 4)).to(device)] if exemplars is None else [torch.tensor(exemplars).to(device)]
> labels = torch.zeros((1, 0), dtype=torch.long).to(device)
> 
> targets = [{
>     "image_id": torch.tensor([0]),
>     "annotations": [],
>     "caption": text + " .",
>     "exemplars": exemplars_tensor[0]
> }]
> 
> with torch.no_grad():
>     model_output = model(samples, exemplars_tensor, labels, targets)
> 
> logits = model_output["pred_logits"].sigmoid()[0]
> boxes = model_output["pred_boxes"][0]
> 
> CONF_THRESH = 0.10
> scores = logits.max(dim=-1).values
> box_mask = scores > CONF_THRESH
> boxes = boxes[box_mask].cpu().numpy()
> scores = scores[box_mask].cpu().numpy()
> 
> print(f"Detected center points count: {len(boxes)}")
> 
> return image, boxes, scores
> ```
> 
> def plot_results(image, boxes, scores, output_path): draw = ImageDraw.Draw(image) font = ImageFont.load_default()
> 
> ```
> color = "red"
> radius = 5  # 定义圆点的半径
> for box, score in zip(boxes, scores):
>     box = box * np.array([image.width, image.height, image.width, image.height])
>     x_c, y_c, w, h = box
>     # 获取中心点坐标
>     x0, y0 = x_c, y_c
> 
>     # 确保中心点在图像范围内
>     x0 = max(0, min(x0, image.width - 1))
>     y0 = max(0, min(y0, image.height - 1))
> 
>     # 绘制中心点为红色的圆圈
>     draw.ellipse([x0 - radius, y0 - radius, x0 + radius, y0 + radius], outline=color, width=2)
> 
> image.save(output_path)
> ```
> 
> def main(args): model, transform = build_model_and_transforms(args)
> 
> ```
> os.makedirs(args.output_folder, exist_ok=True)
> 
> image_files = [f for f in os.listdir(args.input_folder) if f.lower().endswith(('.png', '.jpg', '.jpeg', '.gif'))]
> 
> # 如果提供了exemplar文件，将exemplars加载
> exemplars_data = None
> if args.exemplars is not None:
>     with open(args.exemplars, 'r') as f:
>         exemplars_data = json.load(f)
> 
> for image_file in tqdm(image_files, desc="Processing images"):
>     input_path = os.path.join(args.input_folder, image_file)
>     output_path = os.path.join(args.output_folder, f"{os.path.splitext(image_file)[0]}_counted.png")
>     
>     # 如果提供了exemplars，使用相应的exemplar
>     exemplars = None
>     if exemplars_data and image_file in exemplars_data:
>         exemplars = exemplars_data[image_file]
> 
>     image, boxes, scores = process_image(model, transform, input_path, args.text, args.device, exemplars)
>     plot_results(image, boxes, scores, output_path)
>     
>     print(f"Processed {image_file}. Predicted count: {boxes.shape[0]}")
> ```
> 
> if **name** == "**main**": parser = argparse.ArgumentParser("CountGD Single Image Inference", parents=[get_args_parser()]) args = parser.parse_args() main(args)
> 
> Let me know if you have any suggestions or thoughts on why this might be happening or if there’s anything else we should try.
> 
> Best regards,

does this code run when you add the exemplars? i ran it and it works fine with just text prompts but i'm facing some issue when i add the exemplars. the issue is coming from the labels particularly
