### ISSUE TITLE
Question about inference on a single example

### ISSUE THREAD

**Issue by shubhramishra07** [niki-amini-naieni/CountGD#19]
Hi!

I was wondering if the CountGD model can be used to run inference on a single example? I’m using it as part of an ensemble, and want to be able to run the model (from code) on one image with a caption but no exemplars.

Thank you!

**Comment by niki-amini-naieni** [comment]
Yes, you can. Have you checked out the file app.py in the code for the CountGD app? Here is a link: https://huggingface.co/spaces/nikigoli/countgd/blob/main/app.py
<img width="756" alt="image" src="https://github.com/user-attachments/assets/02d1b182-1f2e-4a9d-96ac-219eac27f3b3">

I have highlighted the relevant function above. It is called ```count_main``` and works even if no visual exemplars are provided and only  text is provided.
