### ISSUE TITLE
training script

### ISSUE THREAD

**Issue by eeeric-code** [niki-amini-naieni/CountGD#3]
Could you please provide the training script as the inference script already provided? Thanks!

**Comment by niki-amini-naieni** [comment]
Hi, yes, I am working on this. This issue is related to https://github.com/niki-amini-naieni/CountGD/issues/1.

**Comment by niki-amini-naieni** [comment]
Hi, thank you for your interest. The code and instructions are now available here: https://github.com/niki-amini-naieni/CountGD/blob/main/training.md.
