### ISSUE TITLE
Complete result of CountBench

### ISSUE THREAD

**Issue by Kkkkkz21** [niki-amini-naieni/CountGD#6]
Excuse me, where else can I see the complete results of CountBench besides Figure 4?

**Comment by niki-amini-naieni** [comment]
Hello, thank you for your question. We include the results in the last two rows of Table 2. We compare to CounTX on CountBench. I have pasted an image of the table with a yellow arrow pointing at the results below.
![IMG_9210](https://github.com/user-attachments/assets/f410baa9-6fb2-4df7-bd0c-ca258f2f9de2)

**Comment by Kkkkkz21** [comment]
Oh, I saw it, thank you!

**Comment by Kkkkkz21** [comment]
> Hello, thank you for your question. We include the results in the last two rows of Table 2. We compare to CounTX on CountBench. I have pasted an image of the table with a yellow arrow pointing at the results below. ![IMG_9210](https://private-user-images.githubusercontent.com/61301874/359625619-f410baa9-6fb2-4df7-bd0c-ca258f2f9de2.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQyMTc2NDcsIm5iZiI6MTcyNDIxNzM0NywicGF0aCI6Ii82MTMwMTg3NC8zNTk2MjU2MTktZjQxMGJhYTktNmZiMi00ZGY3LWJkMGMtY2EyNThmMmY5ZGUyLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgyMVQwNTE1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZDMyMGY2NmE5ZDEwMjEwZDNhYzRlMDIxODlmYzgyZmM2MDA0MTczNzYwZTk1MDQ1Njg3NjgyNmY5OTNiMTk5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.28qZ_XQyw30_o24Fu4muKMhzIjXtY1-oESoaWK_L-7o)

Oh, I saw it, thank you!

**Comment by hongge831** [comment]
@niki-amini-naieni 
can you provide the descriptions and keywords for CountBench you generated for us?

**Comment by niki-amini-naieni** [comment]
Yes. The descriptions and keywords are available [here](https://github.com/niki-amini-naieni/CountGD/blob/main/data/fsc147_gdino/CountBench.json). The code to test the pretrained model on CountBench and reproduce the results of the paper is [here](https://github.com/niki-amini-naieni/CountGD/blob/main/test_countbench.py). You can download the CountBench images [here](https://drive.google.com/file/d/1kGUzF8C-z7HOBvMWjLhrUQtvY5bx6fQ9/view?usp=sharing).
