### ISSUE TITLE
Training Instruction

### ISSUE THREAD

**Issue by XLoveRye** [niki-amini-naieni/CountGD#9]
Excellent work! 
There's no doubt CountGD has strong generalizability, while I just need to finetune it on my own dataset for possible better performance.
Although the training code has been uploaded, it will be more helpful to me if there is an instruction on how to train the CountGD on a different dataset instead of FSC-147. Could you provide a detailed guide if possible? Thanks!

**Comment by niki-amini-naieni** [comment]
Hi, thank you for your interest. The code and instructions are now available here: https://github.com/niki-amini-naieni/CountGD/blob/main/training.md.
